#!/bin/bash

DIR=`dirname $0`
DIR="$(cd $DIR; pwd)"

ARCH=`arch`
if [ "$ARCH" = "armv6l" ]; then
	sed -i 's/^FROM .*/FROM arm32v6\/alpine/g' $DIR/vpnlaunchpad/Dockerfile
elif [ "$ARCH" = "armv7l" ]; then
	sed -i 's/^FROM .*/FROM arm32v6\/alpine/g' $DIR/vpnlaunchpad/Dockerfile
else
	sed -i 's/^FROM .*/FROM alpine/g' $DIR/vpnlaunchpad/Dockerfile
fi

docker build --rm=true -t samuelhbne/vpnlaunchpad $DIR/vpnlaunchpad/
echo

mkdir -p $DIR/.vpn-launchpad $DIR/.aws
if [ ! -f $DIR/.aws/config ]; then
        echo -e '[default]\nregion = ap-northeast-1\noutput = json\n'>>$DIR/.aws/config
fi
BVLPC=`docker ps -a| grep vlp-alpine|wc -l`
if [ $BVLPC -gt 0 ]; then
        docker stop vlp-alpine; docker rm vlp-alpine
fi

DOCKERCMD="docker run --user `id -u`:`id -g` --rm=true --name vlp-alpine -v $DIR:/vpn-launchpad -it samuelhbne/vpnlaunchpad"

if [[ $# = 0 ]]; then
	$DOCKERCMD /vpn-launchpad/vlp-menu
else
	while [[ $# > 0 ]]; do
		act="$1"
		case $act in
			--init)
				$DOCKERCMD /usr/bin/aws configure
				shift
				;;
			--build)
				$DOCKERCMD /vpn-launchpad/vlp-build
				shift
				;;
			--query)
				$DOCKERCMD /vpn-launchpad/vlp-query
				shift
				;;
			--purge)
				$DOCKERCMD /vpn-launchpad/vlp-purge
				shift
				;;
			*)
				$DOCKERCMD /vpn-launchpad/vlp-menu
				shift
				;;
		esac
	done
fi
