#!/bin/bash

DIR=`dirname $0`
DIR="$(cd $DIR; pwd)"

DKUID=`id -u`
DKGID=`id -g`

docker build --build-arg DKUID="$DKUID" --build-arg DKGID="$DKGID" -f $DIR/vpnlaunchpad/Dockerfile --rm=true -t samuelhbne/vpnlaunchpad:alpine $DIR/vpnlaunchpad/
echo

mkdir -p $DIR/.vpn-launchpad/.aws
if [ ! -f $DIR/.vpn-launchpad/.aws/config ]; then
        echo -e '[default]\nregion = ap-northeast-1\noutput = json\n'>>$DIR/.vpn-launchpad/.aws/config
fi
BVLPC=`docker ps -a| grep vlp-alpine|wc -l`
if [ $BVLPC -gt 0 ]; then
        docker stop vlp-alpine; docker rm vlp-alpine
fi

# docker run --rm=true --name vlp-alpine -v $DIR:/home/ubuntu/vpn-launchpad -v $DIR/.vpn-launchpad/.aws:/home/ubuntu/.aws -v $DIR/.vpn-launchpad:/home/ubuntu/.vpn-launchpad -it samuelhbne/vpnlaunchpad:alpine

DOCKERCMD="docker run --rm=true --name vlp-alpine -v $DIR:/home/ubuntu/vpn-launchpad -v $DIR/.vpn-launchpad/.aws:/home/ubuntu/.aws -v $DIR/.vpn-launchpad:/home/ubuntu/.vpn-launchpad -it samuelhbne/vpnlaunchpad:alpine"

if [[ $# = 0 ]]; then
	$DOCKERCMD vpn-launchpad/vlp-menu
else
	while [[ $# > 0 ]]; do
		act="$1"
		case $act in
			--init)
				$DOCKERCMD "aws configure"
				shift
				;;
			--build)
				$DOCKERCMD vpn-launchpad/vlp-build
				shift
				;;
			--query)
				$DOCKERCMD vpn-launchpad/vlp-query
				shift
				;;
			--purge)
				$DOCKERCMD vpn-launchpad/vlp-purge
				shift
				;;
			*)
				$DOCKERCMD vpn-launchpad/vlp-menu
				shift
				;;
		esac
	done
fi
