#!/bin/bash

DIR=`dirname $0`
DIR="$(cd $DIR; pwd)"

act="$1"
case $act in
	build)
		shift
		$DIR/bin/lproxy-build $*
		;;
	status)
		shift
		$DIR/bin/lproxy-status $*
		;;
	purge)
		shift
		$DIR/bin/lproxy-purge $*
		;;
	*)
		shift
		echo "lproxy <command> [options] <brook|shadowsocks>"
		echo "  build            -- Build local proxy container."
		echo "    --from-src     -- Build local proxy container from source rather than docker image downloading."
		echo "      brook        -- Build local proxy container that connect to VPN server via Brook connector"
		echo "      shadowsocks  -- Build local proxy container that connect to VPN server via ShadowSocks connector"
		echo "  status           -- Check local proxy container status."
		echo "  purge            -- Destory local proxy container."
		;;
esac
