#!/bin/bash

DIR=`dirname $0`
DIR="$(cd $DIR; pwd)"

cp -a $DIR/vpnlaunchpad/Dockerfile.in $DIR/vpnlaunchpad/Dockerfile

ARCH=`arch`
case $ARCH in
	armv6l|armv7l)
		sed -i.bak  's/^FROM .*/FROM arm32v6\/alpine/g' $DIR/vpnlaunchpad/Dockerfile && rm $DIR/vpnlaunchpad/Dockerfile.bak
		;;
	x86_64|i686)
		sed -i.bak  's/^FROM .*/FROM alpine/g' $DIR/vpnlaunchpad/Dockerfile && rm $DIR/vpnlaunchpad/Dockerfile.bak
		;;
	*)
		echo "Unsupported arch"
		exit
		;;
esac

DKUID=`id -u`
DKGID=`id -g`
sed -i.bak "s/^ENV DKUID .*/ENV DKUID ${DKUID}/" $DIR/vpnlaunchpad/Dockerfile && rm $DIR/vpnlaunchpad/Dockerfile.bak
sed -i.bak "s/^ENV DKGID .*/ENV DKGID ${DKGID}/" $DIR/vpnlaunchpad/Dockerfile && rm $DIR/vpnlaunchpad/Dockerfile.bak

echo "Building vpnlaunchpad image..."
docker build --rm=true -t samuelhbne/vpnlaunchpad $DIR/vpnlaunchpad/
echo

mkdir -p $DIR/.vpn-launchpad $DIR/.aws
if [ ! -f $DIR/.aws/config ]; then
        echo -e '[default]\nregion = ap-northeast-1\noutput = json\n'>>$DIR/.aws/config
fi
BVLPC=`docker ps -a| grep vlp-alpine|wc -l`
if [ $BVLPC -gt 0 ]; then
        docker stop vlp-alpine; docker rm vlp-alpine
fi

DOCKERCMD="docker run --user `id -u`:`id -g` --rm=true --name vlp-alpine -v $DIR:/home/vlp -it samuelhbne/vpnlaunchpad"

if [[ $# = 0 ]]; then
	$DOCKERCMD /home/vlp/bin/vlp-menu
else
	while [[ $# > 0 ]]; do
		act="$1"
		case $act in
			--init)
				$DOCKERCMD /usr/bin/aws configure
				$DOCKERCMD /home/vlp/bin/vlp-random
				shift
				;;
			--build)
				$DOCKERCMD /home/vlp/bin/vlp-build
				shift
				;;
			--query)
				$DOCKERCMD /home/vlp/bin/vlp-query
				shift
				;;
			--purge)
				$DOCKERCMD /home/vlp/bin/vlp-purge
				shift
				;;
			--random)
				$DOCKERCMD /home/vlp/bin/vlp-random
				shift
				;;
			*)
				$DOCKERCMD /home/vlp/bin/vlp-menu
				shift
				;;
		esac
	done
fi
