#!/bin/bash

DIR=`dirname $0`
VLPHOME="$HOME/.vpn-launchpad"
UBUNTUVER=bionic

PROFILE="default"
REGION=`aws configure get region`
STACKID="vlp-$UBUNTUVER"

if [ ! -z $1 ]; then
	STACKID="$1";
fi

echo "Querying Instance of $STACKID..."
aws --profile $PROFILE --region $REGION --output table ec2 describe-instances --filters "Name=key-name,Values=$STACKID-key" --query 'Reservations[].Instances[0].PublicIpAddress'
aws --profile $PROFILE --region $REGION --output table ec2 describe-security-groups --group-names $STACKID-sg --query "SecurityGroups[*].{Name:GroupName}"

echo
IPADDR=`aws --profile $PROFILE --region $REGION --output text ec2 describe-instances --filters "Name=key-name,Values=$STACKID-key" --query 'Reservations[].Instances[0].PublicIpAddress'`

if [ ! -z "$IPADDR" ]; then
	echo "VPN server is up on $IPADDR"
else
	echo "Server not found"
fi
