#!/bin/bash

DIR=`dirname $0`
DIR="$(cd $DIR; pwd)"

VLPCMD=$DIR/docker-vlp

echo "Query VPS IP address..."
VPSIP=`$VLPCMD --query|grep "VPN SERVER:"|cut -d ':' -f2|cut -d' ' -f2|tr -d '\r\n'`

case $VPSIP in
	"None")
		echo "VPS not found."
		exit 0
		;;
	"")
		echo "VPS not found."
		exit 0
		;;
	*)
		echo "Found VPS: $VPSIP"
		echo "Setting up local proxy daemon..."
		cp -a $DIR/server-ssserver/ssserver.env $DIR/client-sslocal/
		sed -i "s/SSHOST=.*/SSHOST=$VPSIP/g" $DIR/client-sslocal/sslocal.env
		$DIR/client-sslocal/sslocal.sh
		echo "Done."
		echo
		echo
		. $DIR/client-sslocal/sslocal.env
		echo "Found VPS: $VPSIP"
		sleep 5

		echo
		echo "Check local HTTP PROXY on TCP:$HTTPPORT ..."
		echo
		echo "curl -x http://127.0.0.1:$HTTPPORT http://ifconfig.co"
		curl -x http://127.0.0.1:$HTTPPORT ifconfig.co

		echo
		echo "Check local SOCKS PROXY on TCP:$SOCKSPORT ..."
		echo
		echo "curl -x socks5://127.0.0.1:$SOCKSPORT http://ifconfig.co"
		curl -x socks5://127.0.0.1:$SOCKSPORT ifconfig.co

		echo
		echo "Check local DNS PROXY on UDP:$DNSPORT ..."
		echo
		echo "dig +short @127.0.0.1 -p $DNSPORT twitter.com"
		dig +short @127.0.0.1 -p $DNSPORT twitter.com
		;;
esac
