#!/bin/bash

DIR=`dirname $0`
VLPHOME="$HOME/.vpn-launchpad"
UBUNTUVER=xenial

PROFILE="default"
REGION=`aws configure get region`
STACKID="vlp-$UBUNTUVER"

if [ ! -z $1 ]; then
	STACKID="$1";
fi

echo "Querying Instance of $STACKID..."
INSTID=`aws --profile $PROFILE --region $REGION --output text ec2 describe-instances --filters "Name=key-name,Values=$STACKID-key" --query 'Reservations[].Instances[0].InstanceId'`

echo "Deleting Instance of $STACKID..."
aws --profile $PROFILE --region $REGION --output text ec2 terminate-instances --instance-id $INSTID


for i in `seq 5 -1 0`; do
  echo "Waiting Instance shutdown..."
  sleep 5
  echo "Deleteing Security Group of $STACKID..."
  aws --profile $PROFILE --region $REGION --output text ec2 delete-security-group --group-name $STACKID-sg
  if [ "$?" -eq "0" ]; then
    break;
  fi
  echo "Security Group of $STACKID deletion Failed. $i try left."
done


echo "Deleting SSH Key-Pair of $STACKID..."
aws --profile $PROFILE --region $REGION --output text ec2 delete-key-pair --key-name $STACKID-key
rm -rf $VLPHOME/$STACKID-key.pem

