FROM arm32v6/python:3-alpine

MAINTAINER Samuel Huang "samuelh2006@gmail.com"

RUN addgroup -g 1000 ubuntu && adduser -G ubuntu -u 1000 -s /bin/ash -h /home/ubuntu -D ubuntu
RUN apk update && apk add git openssh gcc musl-dev libffi-dev openssl-dev make bash

RUN su - ubuntu -c "pip install --user awscli && echo 'export PATH=$PATH:~/.local/bin:~/bin/'>>.profile"

ENTRYPOINT ["su", "-", "ubuntu", "-c"]
CMD ["'vpn-launchpad/vlp-menu'"]
