name: docker-build

on:
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push AMD64
        uses: docker/build-push-action@v2
        with:
            context: vpnlaunchpad
            file: Dockerfile.amd64
            platforms: linux/amd64
            push: true
            tags: |
              samuelhbne/vpnlaunchpad:amd64
              samuelhbne/vpnlaunchpad:latest
      -
        name: Build and push ARM64v8
        uses: docker/build-push-action@v2
        with:
            context: vpnlaunchpad
            file: Dockerfile.arm64
            platforms: linux/arm64
            push: true
            tags: samuelhbne/vpnlaunchpad:arm64
      -
        name: Build and push ARM32v6
        uses: docker/build-push-action@v2
        with:
            context: vpnlaunchpad
            file: Dockerfile.arm
            platforms: linux/arm/v6
            push: true
            tags: samuelhbne/vpnlaunchpad:arm
